### PR TITLE
Translate docs to pt br

### PR DESCRIPTION
**Pull request by carlosdelfino**

### CODE REVIEW

**Comment by Guillaume-Savaton-ESEO** [comment]
Sorry. I forgot to tell you.
Since emulsiV now supports 32 registers, it is compatible with the RV32I architecture spec.

I have made several changes to the documentation.
The biggest change is in the part where I explain how to build the GNU toolchain for RV32E.
Now I recommend using a pre-built toolchain (`riscv64-unknown-elf-...`).

**Comment by carlosdelfino** [comment]
I saw the changes, but did not realize it had affected the documentation.
No problem, I still make the adjustments today.

**Comment by carlosdelfino** [comment]
There was no change in the documentation regarding the new registrars.

**Comment by Guillaume-Savaton-ESEO** [comment]
Please see commits 5537b5eb1e54683912c4f18886ac15333f8bbc3d and 867fa0f49eb067494610fd8a88697a66494c35a2 for recent changes in the documentation.

**Comment by carlosdelfino** [comment]
I'm sorry, corrected.

**Comment by Guillaume-Savaton-ESEO** [comment]
Thanks. I have merged your changes.

Is there a specific reason for having a stylesheet in the `pt_BR` folder?
I think I could as well link your `index.html` to the CSS file already present in `doc/`.

**Comment by carlosdelfino** [comment]
The page presented strange behavior with a different layout than the original, so I thought it would be better to replicate it. Even though I refer to "../"

**Pull request merged**
